<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 1. The Basics -->
    <groupId>org.example</groupId>
    <artifactId>junitdemo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.12.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <!-- 2. Build Settings -->
    <reporting>
        <plugins>
            <!-- This plugin should be downloaded correctly -->
            <!-- Error message is due to IDE glitch so just ignore it (by Chád) -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>3.5.2</version>
                <!-- If we only want to display failed tests... -->
                <configuration>
<!--                    <showSuccess>false</showSuccess>-->
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <build>
        <plugins>
            <!-- Maven-site -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.21.0</version>
            </plugin>
            <!-- JaCoCo -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <!-- Customize functionality -->
                <executions>
                    <execution>
                        <id>jacoco-prepare</id>
<!--                        <phase>initialize</phase>-->
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>jacoco-report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <!-- 3. More Project Information -->
    <name/>
    <description/>
    <url/>
    <inceptionYear/>
    <licenses/>
    <organization/>
    <developers/>
    <contributors/>


    <!-- 4. Environment Settings -->
    <issueManagement/>
    <ciManagement/>
    <mailingLists/>
    <scm/>
    <prerequisites/>
    <repositories/>
    <pluginRepositories/>
    <distributionManagement/>
    <profiles/>



</project>