###################
##### TESTING #####
###################
info.school.name=free2learn
info.app.name=My Legendary Gradebook
info.app.description=an unprecedented way to track student grades!
info.app.version=1.0.0

## Server Properties
server.port=1500

## H2 Test Database creds
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# SQL Scripts

sql.script.create.student=INSERT INTO student (firstname, lastname, email_address) VALUES ('Tom', 'Riddle', 'hi-im-tom@gmail.com')
sql.script.create.grade.history=INSERT INTO history_grade (student_id, grade) VALUES (1, 100.00)
sql.script.create.grade.math=INSERT INTO math_grade (student_id, grade) VALUES (1, 100.00)
sql.script.create.grade.science=INSERT INTO science_grade (student_id, grade) VALUES (1, 100.00)

sql.script.delete.student=DELETE FROM student; ALTER TABLE student ALTER COLUMN id RESTART WITH 1
sql.script.delete.grade.history=DELETE FROM history_grade; ALTER TABLE history_grade ALTER COLUMN id RESTART WITH 1
sql.script.delete.grade.math=DELETE FROM math_grade; ALTER TABLE math_grade ALTER COLUMN id RESTART WITH 1
sql.script.delete.grade.science=DELETE FROM science_grade; ALTER TABLE science_grade ALTER COLUMN id RESTART WITH 1