####################
##### MAIN APP #####
####################
info.school.name=free2learn
info.app.name=My Legendary Gradebook
info.app.description=an unprecedented way to track student grades!
info.app.version=1.0.0

## Server Properties
server.port=1500

## Spring Datasource

spring.datasource.url=jdbc:mysql://localhost:3306/spring-testing
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Logging

#logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.jdbc.bind=TRACE